name       : sympy
version    : '1.7'
release    : 9
source     :
    - https://github.com/sympy/sympy/archive/sympy-1.7.tar.gz : 528031f56b63fddaea88e4bf62b97a09f26af1004b9b87fce6b60d5c1bd4d904
homepage   : https://www.sympy.org
license    : BSD-3-Clause
component  : office.maths
summary    : A computer algebra system written in pure Python
description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a full-featured computer algebra system (CAS) while keeping the code as simple as possible in order to be comprehensible and easily extensible. SymPy is written entirely in Python.
builddeps  :
    - pkgconfig(python3)
    - python-mpmath
rundeps    :
    - python-mpmath
build      : |
    %python3_setup
install    : |
    %python3_install
