name       : sympy
version    : '1.1'
release    : 2
source     :
    - https://github.com/sympy/sympy/archive/sympy-1.1.tar.gz : 7261056d88edbf8b3211dda8cec453234d5a787a4a50ec0a4898f1b74a88d6d6
license    : BSD-3-Clause
component  : office.maths
summary    : A computer algebra system written in pure Python
description: |
    A computer algebra system written in pure Python
builddeps  :
    - pkgconfig(python-3.5)
    - python3-mpmath
rundeps    :
    - python3-mpmath
build      : |
    %python3_setup
install    : |
    %python3_install
