name       : sympy
version    : 1.7.1
release    : 10
source     :
    - https://github.com/sympy/sympy/archive/sympy-1.7.1.tar.gz : 088ad11a91be822765d33d09ae6dc82c6a54d033167e3cc328cd84f84115e3a8
homepage   : https://www.sympy.org
license    : BSD-3-Clause
component  : office.maths
summary    : A computer algebra system written in pure Python
description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a full-featured computer algebra system (CAS) while keeping the code as simple as possible in order to be comprehensible and easily extensible. SymPy is written entirely in Python.
builddeps  :
    - pkgconfig(python3)
    - python-mpmath
rundeps    :
    - python-mpmath
build      : |
    %python3_setup
install    : |
    %python3_install
