name       : sympy
version    : 1.10.1
release    : 16
source     :
    - https://github.com/sympy/sympy/releases/download/sympy-1.10.1/sympy-1.10.1.tar.gz : 5939eeffdf9e152172601463626c022a2c27e75cf6278de8d401d50c9d58787b
homepage   : https://www.sympy.org
license    : BSD-3-Clause
component  : office.maths
summary    : A computer algebra system written in pure Python
description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a full-featured computer algebra system (CAS) while keeping the code as simple as possible in order to be comprehensible and easily extensible. SymPy is written entirely in Python.
builddeps  :
    - pkgconfig(python3)
    - python-mpmath
rundeps    :
    - python-mpmath
build      : |
    %python3_setup
install    : |
    %python3_install
