name       : sympy
version    : 1.1.1
release    : 5
source     :
    - https://github.com/sympy/sympy/archive/sympy-1.1.1.tar.gz : 4420a1e31939244d7ea73e164fdbb0d4a6a2e764d56e5bf632f57a988f13767f
license    : BSD-3-Clause
component  : office.maths
summary    : A computer algebra system written in pure Python
description: |
    A computer algebra system written in pure Python
builddeps  :
    - pkgconfig(python3)
    - python3-mpmath
    - python-mpmath
rundeps    :
    - python3-mpmath
    - python-mpmath
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
